### PR TITLE
Fixes #212

### LINKED ISSUE #212: Charts rendered only when browser refreshes when using page caching
I noticed that when I'm using page caching (gem 'actionpack-page_caching'), the charts are rendered only when a full refresh is made (i.e. not when navigating to the chart page using internal links, only when pressing f5).
I think it may be something related to encapsulate_js method in layout_helper.rb : it checks for the referrer (request_is_referrer) to conditionally renders a block of js, and when the page is fully cached, it doesn't have the chance to render it differently on the second call (when not refreshing).

Anyone already experienced this? Any thoughts on using page caching with lazy_highcharts?

### PR DESCRIPTION
**Pull request by lamoglia**
The change is to load the charts using $(document).ready instead of window.onload to allow charts to render even with page caching enebled (issue #212)

Some logic related to specific turbolinks vesions was removed, need to confirm if it is ok, I haven't seen any side-effects.

### CODE REVIEW

**Comment by xiaods** [comment]
LGTM

**Comment by michelson** [comment]
Hi , thanks for this code contribution @lamoglia 
Have you tested this with turbolinks 5 or < 5 ?
I think remove turbolinks or vanilla js is a no go. 
I would like to reproduce the issue #212 , in our dummy application , ¿are you using turbolinks in your app?

**Comment by lamoglia** [comment]
I've tested with turbolinks (2.5.3). 
Why those "page:load" listeners are needed when using turbolinks? 
I thought that $(document).ready does that job already.

**Comment by michelson** [comment]
Hi @lamoglia, Those are the turbolink's `$(document).ready` listeners needed to trigger the callbacks when page load. 
This: `$(document).on('page:load', ready)` is the jQuery version for turbolinks, the analog for `$(document).ready(ready)`.
In Turbolinks 5 by the way, `page:load` was changed to `turbolinks:load`, that's why we implement the referer logic and Turbolink version < 5 and >=5 checks.
we've Turbolinks 5 support merged a month ago from PR #214 , so remove it in this release makes no sense. 
are you using turbolinks along with page caching ?

regards

**Comment by lamoglia** [comment]
Ok, I'll try to update my project's turbolinks to >=5 to see if something goes wrong and report back ASAP

**Comment by michelson** [comment]
ok, note that you can disable turbolinks caching https://github.com/turbolinks/turbolinks#opting-out-of-caching

**Comment by dredupuika** [comment]
This is a no go!
The problem is that when rails native view caching is on the first time a chart is rendered it gets wrapped in the onload event. And when turbolinks gets the view it fetches the same html from the cache bypassing encapsulate_js. This way we end up with onload instead of turbolinks:load.

My guess is that on Turbolinks 5 even if it's not an XHR request you should go with turbolinks:load.
Will test this tomorrow.

**Comment by dredupuika** [comment]
anyhow [this](https://github.com/dredupuika/lazy_high_charts/commit/a55e7ec22ceac379a193485e2ddf3bef55da7ca5) fixes it for turbolinks 5!

**Pull request closed without merging**
