### PR TITLE
support turbolinks 5

### PR DESCRIPTION
**Pull request by huhuanming**

### CODE REVIEW

**Comment by michelson** [comment]
Hi! , thanks for this PR

question: the ruby update means that from this point we won't support older ruby versions ?

**Comment by huhuanming** [comment]
in order to pass ci, i changed ruby version to 2.2.3.
it can work on old ruby versions, no problem.
🤔

**Comment by JonasNielsen** [comment]
Thanks @huhuanming, worked splendidly for me

**Comment by xiaods** [comment]
+1

**Comment by michelson** [comment]
thanks! @huhuanming

**Comment by 1v** [comment]
No version bump?

**Pull request merged**
