### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TomasBarry**
In case anyone else encounters issues integrating lazy_high_charts into Active Admin I've updated the README

### CODE REVIEW

**Comment by TomasBarry** [comment]
@michelson can we merge this or discuss?

**Comment by michelson** [comment]
Hi @TomasBarry , this seems to be very active_admin specific, what if someone needs to integrate it on rails_admin ? it don't make sense to add this in README file, maybe it could be added on the WIKI. 
what you think about that ?

best

**Comment by TomasBarry** [comment]
@michelson adding to the wiki would be perfect. Agreed that it is specific to Active Admin

**Comment by michelson** [comment]
thanks!

**Pull request closed without merging**
