### PR TITLE
in HighChart#full_options   the@date should be @series_data

### PR DESCRIPTION
**Pull request by 759803573**
I want use phantomjs generate image,when I use HighChart to generate JSON data ,the data  hava a problem
Contrast  layout_helper#build_html_output  ,I think should change @data to @series_data

sorry my english is not well.

### CODE REVIEW

**Comment by xiaods** [comment]
@759803573 could you please remove useless file lib/lazy_high_charts/high_chart.rb~

**Comment by 759803573** [comment]
oh

**Comment by xiaods** [comment]
@759803573 you can git rebase and git push -f to merge two commit to one commit, then push -f again.
by the way, a testing is welcome.

**Comment by 759803573** [comment]
Thank you for your patience to teach

**Pull request merged**
