### PR TITLE
Format DateTime objects within the data items array.

### PR DESCRIPTION
**Pull request by jacksonh**
Highcharts allows specifying data with irregular time intervals as tuples of (date, value) objects.

Another side-effect of this patch is lists of DateTime objects will be properly formatted into JS date objects.

This resolves the issue presented in #82.

### CODE REVIEW

**Comment by michelson** [comment]
Hi @jacksonh , thanks for this PR
I will try to fix the CI build to merge this asap

best!

**Comment by jacksonh** [comment]
Thanks @michelson, looks like #214 fixes this. Let me know if you want me to rebase.

**Comment by michelson** [comment]
Hi @jacksonh , that would be great, please go ahead

**Comment by jacksonh** [comment]
OK, I will wait until that one is merged and rebase. Not sure if you want to move to Ruby 2+ or fix the CI build.

**Comment by jacksonh** [comment]
@michelson rebased on current master, but seeing the same 1.4 error, any ideas?

**Comment by CUnknown** [comment]
What is the status on this? I would really like this feature!

**Pull request closed without merging**
